M48
; DRILL file {KiCad 9.0.1} date 2025-07-17T12:26:56-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-17T12:26:56-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X121.92Y-100.5
T2
X107.5Y-86.5
X107.5Y-122.5
X181.5Y-86.5
X181.5Y-122.5
M30
